### ISSUE TITLE
Welcome email content

### ISSUE THREAD

**Issue by mrkart** [mrkart/certifi#3]
Email Template
Subject: [Opticore Engineering] has invited you to Certifi.ly 

Message., Hello KarthiKeyan., 
Welcome to Certifi.ly, Easy way to collect & store your professional certificates, documents, memberships, cards & tickets as NFTs on Flow blockchain. [Opticore Engineering] invited you to use certifi.ly to access your professional NFT documents from them and around the world. 

Credentialshttps://alpha.certifi.ly/login [Environment based domain/subdomain]
Username: kart@certifi.ly
Password: password 

Every new certifi.ly user gets a walletless flow blockchain account on-boarding for free. 
Once you login to Certifi.ly & Connected your Flow Wallet (Blocto)., Below Flow account ownership will be transferred to your connected flow account.

Your Certifi.ly Flow Account for kart@certifi.ly
0x1982389324987234 

Regards,
Certifi.ly Team[www.certifi.ly](https://www.certifi.ly/)
reach@certifi.ly

**Comment by vijaykoushiksekar** [comment]
This content has been applied
